### ISSUE TITLE
Sunshine: SW encoder with AMD

### ISSUE THREAD

**Issue by mikrofyr** [timminator/Enhanced-GPU-PV#2]
Hi, cant seem to get HW encoding for sunshine inside VM. It always pick SW and I need to increase min thread count to get okish performance. 

On host itself i get h264_amf out of the box.
Gpu is 7900 xt, latest driver.

Suggestions on how to fix is appreciated.

**Comment by timminator** [comment]
Im pretty sure your problem is caused by the driver version you are using.
In the original project is an issue open that describes exactly your problem. You can find it [here](https://github.com/jamesstringerparsec/Easy-GPU-PV/issues/392).
The latest working driver from AMD seems to be version 24.3.1.
Let me know if that helps to solve your problem.

**Comment by mikrofyr** [comment]
I browsed that ticket but dismissed it as GPU acceleration in games was indeed working for me. However both parsec and sunshine failed at HW encoding video stream.

I downgraded as described in https://github.com/jamesstringerparsec/Easy-GPU-PV/issues/392#issuecomment-2325266373 and it does fix my issue!

Many thanks for pointing me in the right direction.
Will leave a feedback on my case in the other ticket.

**Comment by timminator** [comment]
Hi mikrofyr,
sorry for bothering you again, but i have another question for you since you are running an Amd setup.
I`ve noticed that you also commented in this [thread](https://github.com/jamesstringerparsec/Easy-GPU-PV/issues/342), where we talked about enabling OpenGL and Vulkan support.
I don't know if you still followed this thread but it looks like that for Nvidia users only 32 bit vulkan applications run at the moment.
Now i'm really curious if that's also the case on AMD graphics cards.
Maybe you could try running running the Furmark 64bit and 32bit version and report your findings back?
I would really appreciate it.
If you created the VM with my script, you should be able to reenable the Hyper-V Monitor in the Display settings in Windows to enable OpenGL/Vulkan support, so its a bit easier than in the original repo.
I look forward from hearing from you again. :-)

**Comment by mikrofyr** [comment]
Hi, sorry for late reply.
Tested just now: Both Furmark 32 and 64bit seem to work with my AMD GPU.  (drivers rolled back as in past discussion)
The HyperV display is disabled in monitor setting, no need for the workaround presented. 

PS: My past comment in the thread you mention was with Nvidia card. Since then I  acquired an AMD GPU for GPU-PV due to more VRAM. I should probably re-test my original use case.

**Comment by timminator** [comment]
Thank you for testing it out!
That's very interesting, especially that it works on amd graphics cards without enabling the hyper-v display. Seems like the dream solution.
The 64 bit problem then seems to be a Nvidia problem.
Thank you once again!
